name: financial
description: The Reply Material Design case study. Written in Flutter.

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: 3.0.0
  flare_flutter: 1.5.5
  flutter_masked_text: ^0.8.0
  pull_to_refresh: ^1.5.4
  dio: ^2.1.16
  http: ^0.12.0+2
  carousel_slider: ^1.3.0
  flutter_secure_storage: ^3.3.1
  fluro: '^1.5.1'
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1
  meta: ^1.1.7
  json_serializable: ^3.2.2
  build_runner: ^1.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
