name: financial
description: Save your fundings in the right way.

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.2.0
  flare_flutter: 1.5.5
  flutter_masked_text: ^0.8.0
  pull_to_refresh: ^1.5.4
  dio: ^2.1.16
  http: ^0.12.0+2
  carousel_slider: ^1.3.0
  flutter_secure_storage: ^3.3.1
  fluro: '^1.5.1'
  equatable: ^0.5.1
  meta: ^1.1.7
  json_annotation: ^3.0.0
  json_serializable: ^3.2.2
  build_runner: ^1.7.0
  vibration: ^1.2.1
  shimmer: ^1.0.1
  material_design_icons_flutter: ^3.3.4595
  intl: ^0.16.0
  mobx:
  flutter_mobx:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  mobx_codegen:

flutter_icons:
  android: true
  image_path: 'assets/images/financial.png'

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
